### ISSUE TITLE
mite 的参考

### ISSUE THREAD

**Issue by demo250** [XiaoYuOvO/MITE1.13.2#23]
[MITE·新中文Wiki第二版（v2.1）.pdf](https://github.com/XiaoYuOvO/MITE1.13.2/files/3057975/MITE.Wiki.v2.1.pdf)
[中文合成表.pdf](https://github.com/XiaoYuOvO/MITE1.13.2/files/3057976/default.pdf)

**Comment by XiaoYuOvO** [comment]
知道了,谢谢
